verifying package pkg/spao
aaronbojarski/VerifiedSCION pull request #7
Opened 2024-12-05 09:56 UTC by aaronbojarski

2025-01-21 11:58 UTC, jcp19 requested changes

2025-01-21 11:58 UTC, jcp19 commented on .github/workflows/gobra.yml
> +          timeout: 30m
I'm surprised we need such a large timeout for this package

2025-01-21 11:58 UTC, jcp19 commented on pkg/drkey/drkey.go
>  package drkey
probably it makes sense to either verify this package first before merging spao, otherwise we are assuming a lot of contracts for this file that may later be wrong (like, we are assuming that all pres are true).

2025-01-21 11:58 UTC, jcp19 commented on pkg/slayers/pkt_auth.go
> +// @ ensures   len(o.OptData) == old(len(o.OptData))
why do we need this postcondition? any client that requires this should in principle be able to get it through framing

2025-01-21 11:58 UTC, jcp19 commented on pkg/slayers/pkt_auth.go
> +// @ preserves acc(o.EndToEndOption, R49)
Isn't `R50` enough here? Whenever possible, we should try to be consistent and pick a single fractional permission amount
```suggestion
// @ preserves acc(o.EndToEndOption, R49)
```

2025-01-21 11:58 UTC, jcp19 commented on pkg/slayers/pkt_auth.go
> +// @ decreases
same comments apply here

2025-01-21 11:58 UTC, jcp19 commented on pkg/slayers/pkt_auth.go
> +// @ decreases
...and here

2025-01-21 11:58 UTC, jcp19 commented on pkg/slayers/scion_spec.gobra
> +			s.Path.(*epic.Path).GetBase(ubPath).Valid())
```suggestion
			s.Path.(*epic.Path).GetBase(ubPath).Valid())
```

2025-01-21 11:58 UTC, jcp19 commented on pkg/spao/mac.go
> +// @ ensures   retErr != nil ==> retErr.ErrorMem()
I would rather move the pure conditions about `input` to a pure function that describes what it means for it to be valid:
```
ghost
requires ... // Memory footprint
pure func (m MACInput) Valid(ubuf ...) bool {
    return m.ScionLayer != nil && 
        input.ScionLayer.ValidPathMetaData(ubuf) 
}
```

Then, we can require this in the precondition instead of having the conditions scattered through a long list of pre conditions (also, these conditions do not need to be preserved, as framing should guarantee them)

2025-01-21 11:58 UTC, jcp19 commented on pkg/spao/mac.go
> +// @ preserves acc(input.ScionLayer.Path.Mem(ubuf), R49)
this looks wrong: First, you already have access to `Path.Mem(...)` inside `ScionLayer.Mem(...)`. Second, you are saying that both the scion header and the path were read from the same slice of raw bytes, which can never be true - the path is read at a certain offset of the ubuf, which can be easily computed (search for occurrences of `ubPath` in the codebase to see how this can be computed). As such, the condition in line 81 should be dropped, as it makes the precondition unsatisfiable

2025-01-21 11:58 UTC, jcp19 commented on pkg/spao/mac.go
> +// @ preserves acc(input.ScionLayer, R9)
why do we have to pass access to the fields here if we get them from `input.ScionLayer.Mem`? This just causes contracts to be more complex than they have to and more complicated preconditions to check, which causes longer verification times. Please drop this line

2025-01-21 11:58 UTC, jcp19 commented on pkg/spao/mac.go
> +// @ preserves sl.Bytes(outBuffer, 0, len(outBuffer))
Can it ever be that the `auxBuffer` and `outBuffer` are aliased in the clients? If so, this spec is not permissive enough

2025-01-21 11:58 UTC, jcp19 commented on pkg/spao/mac.go
> +	// @ fold acc(sl.Bytes(auxBuffer[:inputLen], 0, inputLen), R1)
~~Why don't we specify cmac.Write to take `Bytes(...)` of the input, instead of requiring explicit perms? This just causes more annotation overhead on the side of the client and potentially slower verification times because it requires clients to unfold / fold bytes~~

EDIT: I now realize it is because cmac is meant to implement `hash.Hash`, this is a good reminder of a piece of technical debt I need to address. So, nevermind the comment above.

2025-01-21 11:58 UTC, jcp19 commented on pkg/spao/mac.go
> +// @ ensures   retErr == nil ==> m.Mem() && typeOf(m) == type[*cmac.cmac]
Why do we need the condition `typeOf(m) == type[*cmac.cmac]` here? In principle, this should not be allowed, as `cmac.cmac` is a private type of an imported type, and this will soon be rejected by Gobra. If we depend on any particular property of this hash (e.g., block size or size)

2025-01-21 11:58 UTC, jcp19 commented on pkg/spao/mac.go
> +// @ preserves acc(s.Path.Mem(ubuf), R49)
this condition here makes it unsatisfiable again

2025-01-21 11:58 UTC, jcp19 commented on pkg/spao/mac.go
> +// @ preserves acc(s, R9)
and this is unnecessary, as discussed before

2025-01-21 11:58 UTC, jcp19 commented on pkg/spao/mac.go
> +// @ preserves base.WeaklyValid()
This should be a requires because it is a pure assertion: First, `base` is passed by value, not by reference. Snd, `base` in the postcondition still refers to the value stored in `base` in the beginning, as the value stored in it at the end is useless for the client of this function (`base` is, after all, a local variable) - we can discuss this point in a meeting.

At any rate, because of the reasons I mentioned, it is unnecessary to check this postcondition.
```suggestion
// @ requires base.WeaklyValid()
```

2025-01-21 11:58 UTC, jcp19 commented on pkg/spao/mac.go
> +		// @ 	&buf[offset+2:][j] == &buf[offset+2+j]
For technical reasons that we can discuss later, this quantifier is translated to a quantifier with invalid triggers at the viper level (a somewhat obscure gobra bug). I suggest instead that you copy definition of function `AssertSliceOverlap` in file `verification/utils/slices/slices.gobra` from https://github.com/viperproject/VerifiedSCION/pull/387 and that you call it here instead, i.e., you replace this assert stmt by the call `AssertSliceOverlap(buf, offset+2, len(buf))`

2025-01-21 11:58 UTC, jcp19 commented on pkg/spao/mac.go
>  func serializeAuthenticatedData(
I will review `serializeAuthenticatedData` and `zeroOutMutablePath` and the other non-reviewed files after my first comments are answered

2025-01-22 16:30 UTC, aaronbojarski commented on pkg/spao/mac.go
> +// @ preserves sl.Bytes(outBuffer, 0, len(outBuffer))
No they should never be aliased.

2025-01-22 16:35 UTC, aaronbojarski commented on pkg/spao/mac.go
> +// @ ensures   retErr == nil ==> m.Mem() && typeOf(m) == type[*cmac.cmac]
Yes I need the specific specs for cmac here. (`cmac.Sum` should return the full permission to the input buffer, if it is long enough.)

2025-01-23 13:04 UTC, aaronbojarski commented on pkg/slayers/pkt_auth.go
> +// @ ensures   len(o.OptData) == old(len(o.OptData))
Done.

2025-01-23 13:04 UTC, aaronbojarski commented on pkg/slayers/pkt_auth.go
> +// @ preserves acc(o.EndToEndOption, R49)
Done.

2025-01-23 13:05 UTC, aaronbojarski commented on pkg/slayers/pkt_auth.go
> +// @ decreases
Done.

2025-01-23 13:05 UTC, aaronbojarski commented on pkg/slayers/pkt_auth.go
> +// @ decreases
Done.

2025-01-23 13:05 UTC, aaronbojarski commented on pkg/slayers/scion_spec.gobra
> +			s.Path.(*epic.Path).GetBase(ubPath).Valid())
Done.

2025-01-23 13:05 UTC, aaronbojarski commented on pkg/spao/mac.go
> +// @ preserves sl.Bytes(outBuffer, 0, len(outBuffer))
Checked again. Done.

2025-01-23 13:05 UTC, aaronbojarski commented on pkg/spao/mac.go
> +// @ preserves base.WeaklyValid()
Done.

2025-01-23 13:05 UTC, aaronbojarski commented on pkg/spao/mac.go
> +		// @ 	&buf[offset+2:][j] == &buf[offset+2+j]
Done.

2025-01-23 18:48 UTC, aaronbojarski commented on pkg/spao/mac.go
> +// @ preserves acc(s.Path.Mem(ubuf), R49)
Done.

2025-01-23 18:49 UTC, aaronbojarski commented on pkg/spao/mac.go
> +// @ preserves acc(input.ScionLayer, R9)
Done.

2025-01-23 18:50 UTC, aaronbojarski commented on pkg/spao/mac.go
> +// @ preserves acc(input.ScionLayer.Path.Mem(ubuf), R49)
Done.

2025-01-23 18:50 UTC, aaronbojarski commented on pkg/spao/mac.go
> +// @ ensures   retErr != nil ==> retErr.ErrorMem()
Done.

2025-01-23 19:09 UTC, aaronbojarski commented on pkg/spao/mac.go
> +// @ preserves acc(s, R9)
Done.

2025-01-24 10:03 UTC, aaronbojarski commented on pkg/spao/mac.go
> +// @ ensures   retErr == nil ==> m.Mem() && typeOf(m) == type[*cmac.cmac]
Changed it as discussed. Done.

2025-01-30 10:34 UTC, jcp19 commented on pkg/slayers/scion_spec.gobra
> +			s.Path.(*scion.Decoded).GetBase(ubPath).WeaklyValid()) &&
Does `slayers` still verify with this change? Also, why is this weakly valid instead of valid?

2025-01-30 10:34 UTC, jcp19 commented on verification/dependencies/github.com/dchest/cmac/cmac.gobra
> +requires acc(b)
please swap the order of the `requires` and the `preserves`

2025-01-30 10:34 UTC, jcp19 commented on pkg/spao/mac_spec.gobra
> +)
are you sure these imports are necessary?

2025-01-30 10:34 UTC, jcp19 commented on pkg/spao/mac.go
> +		// @ copyOffset := offset
please mark all such variable declarations explicitely as ghost (throughout the pr)

2025-01-30 10:34 UTC, jcp19 commented on pkg/spao/mac.go
> +// @				orig.(*epic.Path).GetBase(ubuf).WeaklyValid())
whenever you need to indent sth in the following line, please add a space after the '@' and one tab. In addition, can't we replace this complicated expression by a call to a new version of `ValidPathMetaData` (let's call it `WeaklyValidPathMetaData`)?

2025-01-31 15:24 UTC, aaronbojarski commented on pkg/spao/mac.go
> +		// @ copyOffset := offset
Done.

2025-01-31 15:24 UTC, aaronbojarski commented on pkg/spao/mac_spec.gobra
> +)
No they are not. Thank you!
Done.

2025-01-31 15:24 UTC, aaronbojarski commented on verification/dependencies/github.com/dchest/cmac/cmac.gobra
> +requires acc(b)
Done.

2025-02-02 12:17 UTC, aaronbojarski commented on pkg/slayers/scion_spec.gobra
> +			s.Path.(*scion.Decoded).GetBase(ubPath).WeaklyValid()) &&
Yes it did. However I did not realize that the other path types used `Valid` and not `WeaklyValid`. I therefore reverted the change and added a `WeaklyValidPathMetaData` function.

2025-02-02 12:22 UTC, aaronbojarski commented on pkg/spao/mac.go
> +// @				orig.(*epic.Path).GetBase(ubuf).WeaklyValid())
I changed the format the way you suggested. 
To use `WeaklyValidPathMetaData` in the precondition I would need to have access to the `slayers.SCION` header struct. (Which we do not have at this point.)
If you prefere a simpler expression here, I could add a separate pure ghost function to the spec that does exactly what this expression does. Please let me know what you think.

2025-02-02 13:11 UTC, jcp19 commented
I will go over this again once the package `drkey` verifies

2025-02-06 12:22 UTC, aaronbojarski commented on .github/workflows/gobra.yml
> +          timeout: 30m
2.5 min:  func ComputeAuthCMAC
  1.5 min:  func initCMAC
17.0 min:  func serializeAuthenticatedData
  2.5 min:  func zeroOutMutablePath
  2.5 min:  func zeroOutWithBase
  3.0 min:  func bigEndianPutUint48

2025-02-07 10:24 UTC, aaronbojarski commented on pkg/drkey/drkey.go
>  package drkey
Done.

2025-02-07 14:34 UTC, jcp19 reviewed
I have a few minor points. After they are addressed, we may go ahead and merge this

2025-02-07 14:34 UTC, jcp19 commented on pkg/spao/mac.go
>  	_ = buf[MACBufferSize-1]
I wonder why they are doing this operation. Is it to make sure that `buf` has at least `MACBufferSize`? If so, it might be worth asking why we do not return an error here but instead cause the code to panic

2025-02-07 14:34 UTC, jcp19 commented on pkg/spao/mac.go
> +		// @ sl.CombineRange_Bytes(ubuf, ubufOffset, ubufOffset+dstAddrBytes, R10)
I think it may be worth moving these operations on slices into an `outline` block

2025-02-07 14:34 UTC, jcp19 commented on pkg/spao/mac.go
> +		// @ sl.CombineRange_Bytes(ubuf, ubufOffset, ubufOffset+srcAddrBytes, R10)
same here

2025-02-07 14:34 UTC, jcp19 commented on pkg/spao/mac.go
> +// @ 	orig.(*epic.Path).GetBase(ubuf).WeaklyValid())
it would make sense to introduce a function for this, and then we can make the implementation of `WeaklyValidPathMetaData` dependent on this new function

2025-02-07 14:34 UTC, jcp19 commented on pkg/spao/mac_spec.gobra
> +pure func (m MACInput) Valid(ubuf []byte) bool {
I would rather call this function `WeaklyValid`

2025-02-07 14:34 UTC, jcp19 commented on pkg/spao/mac_spec.gobra
> +requires acc(m.ScionLayer.Mem(ubuf), _)
under the new semantics of Viper/Gobra, we should change this:
```suggestion
requires m.ScionLayer.Mem(ubuf)
```

2025-02-07 14:34 UTC, jcp19 commented on verification/dependencies/github.com/dchest/cmac/cmac.gobra
> +
please add the line `cmac implements `hash.Hash` in this line to guarantee that the subtyping relation is enforced

2025-02-23 17:50 UTC, aaronbojarski commented on pkg/spao/mac.go
> +		// @ sl.CombineRange_Bytes(ubuf, ubufOffset, ubufOffset+dstAddrBytes, R10)
Done.

2025-02-23 17:50 UTC, aaronbojarski commented on pkg/spao/mac.go
> +		// @ sl.CombineRange_Bytes(ubuf, ubufOffset, ubufOffset+srcAddrBytes, R10)
Done.

2025-02-24 12:27 UTC, aaronbojarski commented on pkg/spao/mac_spec.gobra
> +pure func (m MACInput) Valid(ubuf []byte) bool {
Done.

2025-02-24 12:27 UTC, aaronbojarski commented on pkg/spao/mac_spec.gobra
> +requires acc(m.ScionLayer.Mem(ubuf), _)
Done.

2025-02-24 12:28 UTC, aaronbojarski commented on verification/dependencies/github.com/dchest/cmac/cmac.gobra
> +
Done.

2025-02-24 13:45 UTC, aaronbojarski commented on pkg/spao/mac.go
> +// @ 	orig.(*epic.Path).GetBase(ubuf).WeaklyValid())
Done.

2025-02-26 15:16 UTC, jcp19 commented on pkg/slayers/scion_spec.gobra
> +	return unfolding acc(s.Mem(ub), _) in
Explicit permission amounts are no longer necessary in pure functions
```suggestion
	return unfolding s.Mem(ub) in
```

2025-02-26 15:16 UTC, jcp19 commented on pkg/slayers/scion_spec.gobra
> +requires acc(s.Mem(ub), _)
```suggestion
requires s.Mem(ub)
```

Explicit permission amounts are no longer necessary in pure functions

2025-02-26 15:16 UTC, jcp19 commented on verification/dependencies/github.com/dchest/cmac/cmac.gobra
> +ensures   err == nil && n == len(p)
I don't understand why the condition at line 39 should be there. Isn't it redundant? Also, are you sure that this operation is never meant to fail and that we can always add all elements from `p` to this writer?

2025-02-26 21:43 UTC, aaronbojarski commented on verification/dependencies/github.com/dchest/cmac/cmac.gobra
> +ensures   err == nil && n == len(p)
Yes it was not necessary, sorry. I removed it. (I copied this spec from the default spec of `Write` from `hash.Hash`. So maybe we need to have another look at that in the future.)

And yes I checked the source. It can not fail and it can always add all elements from `p`.

2025-02-27 12:08 UTC, aaronbojarski commented on .github/workflows/gobra.yml
> +          timeout: 30m
Weirdly now it does verify in 10 min locally. However in the CI it still takes 30 min or more...

2025-02-28 13:47 UTC, aaronbojarski commented on .github/workflows/gobra.yml
> +          timeout: 30m
updated numbers for verifying functions individually:

 ```
 3.0 min:  func ComputeAuthCMAC
 2.5 min:  func initCMAC
 4.5 min:  func serializeAuthenticatedData
 5.0 min:  func zeroOutMutablePath
 5.0 min:  func zeroOutWithBase
 4.5 min:  func bigEndianPutUint48
```

2025-03-01 10:53 UTC, jcp19 approved these changes

2025-03-01 16:25 UTC, merged